### ISSUE TITLE
Is there a license intended for this work?

### ISSUE THREAD

**Issue by downeym** [mahmoudgalal/ZeeArchiver#1]
Hi there! I notice that there is currently no license listed in this repo, although the README file does encourage people to build the software from source.

Unfortunately, without a free software or open source license, the code remains "all rights reserved" and I do not have the legal right to build this software as the instructions demonstrate. Is that the authors' intention?

For more details about the results of not having a license, you can read more at: https://choosealicense.com/no-permission/

Also the main page at https://choosealicense.com/ can help with choosing an existing free software or open source license, if that is desired.

Thanks for your consideration!

**Comment by mahmoudgalal** [comment]
Hi @downeym ,
Thanks for clarifying that !.
A Licence is added to the Repo .

**Comment by downeym** [comment]
Thank you so much! I appreciate your contributions.
