### ISSUE TITLE
E_INVALIDARG error when create archive file

### ISSUE THREAD

**Issue by jackyhieu1211-hn** [mahmoudgalal/ZeeArchiver#6]
@mahmoudgalal 
Hello admin.

When I try new version "Migrating to p7zip v16.02" 
I cann't create archive file. 
I get error E_INVALIDARG. Please check. thank you 

```
    Error, SystemException: E_INVALIDARG                
    Error, kFatalError:-2147024809
```

This is CInfo when create archive
 ```
       UpdateMode = EEnum.kAdd;
        SolidIsSpecified = false;
        MultiThreadIsAllowed = true;
        SolidBlockSize = 0;
        NumThreads = -1;
        VolumeSizes = null;
        Level = 5;
        Method = "Deflate";
        Dictionary = -1;
        OrderMode = false;
        Order = 32;
        Options = "";
        EncryptionMethod = "AES256"; //ZIPPro is ""
        SFXMode = false;
        OpenShareForWrite = false;
        ArchiveName = outputPath; //'/storage/emulated/0/DCIM/Screenshots.zip'
        CurrentDirPrefix = null;
        KeepName = false;
        FormatIndex = 41;
        Password = password;
        EncryptHeadersIsAllowed = false;
        EncryptHeaders = false;
```

**Comment by hieuseesaa** [comment]
Compression parameters:ArcName:/storage/emulated/0/Zip/Compressed/ZipPro_20220505.zip,FormatIndex:41,Level:7,Method:Deflate,Dictionary:4294967295,OrderMode:0,order:32,SolidIsSpecified:0,SolidBlockSize:0,MultiThreadIsAllowed:1,NumThreads:0,EncryptionMethod:AES256,EncryptHeadersIsAllowed:0,EncryptHeaders:0,SFXMode:0
`

**Comment by hn-team1102** [comment]
@mahmoudgalal Please check. thank you very much

**Comment by mahmoudgalal** [comment]
> Compression parameters:ArcName:/storage/emulated/0/Zip/Compressed/ZipPro_20220505.zip,FormatIndex:41,Level:7,Method:Deflate,Dictionary:4294967295,OrderMode:0,order:32,SolidIsSpecified:0,SolidBlockSize:0,MultiThreadIsAllowed:1,NumThreads:0,EncryptionMethod:AES256,EncryptHeadersIsAllowed:0,EncryptHeaders:0,SFXMode:0

The above data is inconsistent as **FormatIndex** for **zip** is **52** not **41**, (shift was due 2 newly added formats)
it looks like you created the above values programmatically not using the app interface, Also there was a bug in threading support that i fixed recently for p7Zipv16.02 (enforcing single-threaded execution) in case you missed this commit which led also to compression/extraction errors

**Comment by jackyhieu1211-hn** [comment]
@mahmoudgalal thank you very much. I fixed.
